//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AktivnostiProfiles_Tbl
    {
        public long ID { get; set; }
        public Nullable<int> Aktivnosti_Id { get; set; }
        public Nullable<int> Profile_Id { get; set; }
        public bool IsUsing { get; set; }
    
        public virtual Aktivnosti_Tbl Aktivnosti_Tbl { get; set; }
        public virtual Profil_Tbl Profil_Tbl { get; set; }
    }
}
