//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentPlaces_Tbl
    {
        public long ID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> OcenaId { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public string UserFromId { get; set; }
        public Nullable<double> SingleEvaluation { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Places_Tbl Places_Tbl { get; set; }
        public virtual PlacesOcena_Tbl PlacesOcena_Tbl { get; set; }
    }
}
