//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drustva_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drustva_Tbl()
        {
            this.DrustvaProfile_Tbl = new HashSet<DrustvaProfile_Tbl>();
        }
    
        public int PD_ID { get; set; }
        public string ImeDrustva { get; set; }
        public string AdresaDrustva { get; set; }
        public string Koordinate { get; set; }
        public string AddressNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrustvaProfile_Tbl> DrustvaProfile_Tbl { get; set; }
    }
}
