//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrustvaProfile_Tbl
    {
        public int ID { get; set; }
        public Nullable<int> DrustvaID { get; set; }
        public Nullable<int> ProfileID { get; set; }
    
        public virtual Drustva_Tbl Drustva_Tbl { get; set; }
        public virtual Profil_Tbl Profil_Tbl { get; set; }
    }
}
