//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventComment_tbl
    {
        public long ID { get; set; }
        public string EventDescription { get; set; }
        public string EventTitle { get; set; }
        public Nullable<double> SingleEvaluation { get; set; }
        public string UserID { get; set; }
        public Nullable<int> EventID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
