//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_Tbl
    {
        public int ID { get; set; }
        public string HotelName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> PlaceId { get; set; }
    
        public virtual Country_Tbl Country_Tbl { get; set; }
        public virtual Places_Tbl Places_Tbl { get; set; }
    }
}
