//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacesOcena_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlacesOcena_Tbl()
        {
            this.ComentPlaces_Tbl = new HashSet<ComentPlaces_Tbl>();
        }
    
        public long ID { get; set; }
        public Nullable<double> Level1 { get; set; }
        public Nullable<double> Level2 { get; set; }
        public Nullable<double> Level3 { get; set; }
        public Nullable<double> Level4 { get; set; }
        public Nullable<double> Level5 { get; set; }
        public Nullable<int> PlaceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentPlaces_Tbl> ComentPlaces_Tbl { get; set; }
    }
}
