//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Places_Tbl()
        {
            this.Events_Tbl = new HashSet<Events_Tbl>();
            this.Hotel_Tbl = new HashSet<Hotel_Tbl>();
            this.Restoran_Tbl = new HashSet<Restoran_Tbl>();
            this.AktivnostiPlaces_Tbl = new HashSet<AktivnostiPlaces_Tbl>();
            this.ComentPlaces_Tbl = new HashSet<ComentPlaces_Tbl>();
        }
    
        public int ID { get; set; }
        public string PlaceName { get; set; }
        public string PlaceImage { get; set; }
        public string Description { get; set; }
        public string Subtitle { get; set; }
        public string Coordinates { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events_Tbl> Events_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_Tbl> Hotel_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restoran_Tbl> Restoran_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktivnostiPlaces_Tbl> AktivnostiPlaces_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentPlaces_Tbl> ComentPlaces_Tbl { get; set; }
        public virtual Country_Tbl Country_Tbl { get; set; }
    }
}
