//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profil_Tbl()
        {
            this.DrustvaProfile_Tbl = new HashSet<DrustvaProfile_Tbl>();
            this.Events_Tbl = new HashSet<Events_Tbl>();
            this.AktivnostiProfiles_Tbl = new HashSet<AktivnostiProfiles_Tbl>();
        }
    
        public int ProfilID { get; set; }
        public string UserImage { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> Ocena_Id { get; set; }
        public string UserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrustvaProfile_Tbl> DrustvaProfile_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events_Tbl> Events_Tbl { get; set; }
        public virtual Ocena_Profila_Tbl Ocena_Profila_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktivnostiProfiles_Tbl> AktivnostiProfiles_Tbl { get; set; }
    }
}
