//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restoran_Tbl
    {
        public int ID { get; set; }
        public string RestoranName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> PlacesId { get; set; }
        public string Description { get; set; }
        public string Subtitle { get; set; }
    
        public virtual Country_Tbl Country_Tbl { get; set; }
        public virtual Places_Tbl Places_Tbl { get; set; }
    }
}
