//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponzori_Tbl
    {
        public int Sponzori_ID { get; set; }
        public string ImeSponzora { get; set; }
        public Nullable<int> TipSponzora_id { get; set; }
    
        public virtual Tip_Sponzora_Tbl Tip_Sponzora_Tbl { get; set; }
    }
}
